const Projects = [
  {
    id: 62100998,
    project: "E-COMMERCE",
    role: "FullStack Developer",
    img: "https://res.cloudinary.com/isreal/image/upload/v1687204038/My%20portfolio%20Project/Screenshot_2023-06-19_at_20.40.57_bxfh6q.png",
    source_code: "",
    live_project: "https://piuda.store",
    Technology: [
      "scss",
      "Next js",
      "Node js",
      "express js",
      "mongo DB",
      "cloudnary",
      "Firebase",
    ],
    details:
      "E-commerce store for small scale businesses, Admin can add product to the store, Pick a category, Pick a class, Select price and quantity. edit existing and delete product from store.",
  },
  {
    id: 62156,
    project: "MARINE SERVICING",
    role: "FullStack Developer",
    img: "https://res.cloudinary.com/isreal/image/upload/v1687204042/My%20portfolio%20Project/Screenshot_2023-06-19_at_20.43.04_nxnoz2.png",
    source_code: "",
    live_project: "https://calmwatersltd.com/",
    Technology: [
      "scss",
      "Next js",
      "cloudnary",
      "Firebase",
    ],
    details:
      "Calm Waters Integrated Services Limited is a Nigerian oil & gas, Maritime support services and Logistics Company.",
  },
  {
    id: 6213453,
    project: "E-COMMERCE",
    role: "FullStack Developer",
    img: "https://res.cloudinary.com/isreal/image/upload/v1687204040/My%20portfolio%20Project/Screenshot_2023-06-19_at_20.42.33_bdrzdi.png",
    source_code: "",
    live_project: "https://e-commerce-client-ashen.vercel.app/",
    Technology: [
      "scss",
      "Next js",
      "Node js",
      "express js",
      "mongo DB",
      "cloudnary",
      "Firebase",
    ],
    details:
      "E-commerce store for small scale businesses, Admin can add product to the store, Pick a category, Pick a class, Select price and quantity. edit existing and delete product from store.",
  },
  {
    id: 621543,
    project: "E-COMMERCE",
    role: "FullStack Developer",
    img: "https://res.cloudinary.com/isreal/image/upload/v1687204042/My%20portfolio%20Project/Screenshot_2023-06-19_at_20.43.04_nxnoz2.png",
    source_code: "",
    live_project: "https://houseofhilda.vercel.app/",
    Technology: [
      "scss",
      "Next js",
      "Node js",
      "express js",
      "mongo DB",
      "cloudnary",
      "Firebase",
    ],
    details:
      "E-commerce store for small scale businesses, Admin can add product to the store, Pick a category, Pick a class, Select price and quantity. edit existing and delete product from store.",
  },

  {
    id: 621,
    project: "E-COMMERCE",
    role: "FullStack Developer",
    img: "https://res.cloudinary.com/isreal/image/upload/v1683183812/Screenshot_2023-05-02_at_00.23.30_r9z6fu.png",
    source_code: "",
    live_project: "https://e-commerce-client-ashen.vercel.app/",
    Technology: [
      "scss",
      "Next js",
      "Node js",
      "express js",
      "mongo DB",
      "cloudnary",
      "Firebase",
    ],
    details:
      "E-commerce store for small scale businesses, Admin can add product to the store, Pick a category, Pick a class, Select price and quantity. edit existing and delete product from store.",
  },
  {
    id: 601,
    project: "INSTAGRAM CLONE",
    role: "FullStack Developer",
    img: "https://res.cloudinary.com/isreal/image/upload/v1678477907/My%20portfolio%20Project/Screenshot_2023-03-10_at_20.46.17_mopu9a.png",
    source_code: "https://github.com/JusticeIsreal/My-instagram-clone",
    live_project: "https://ig-clone-by-justice.vercel.app/",
    Technology: ["Tailwind", "Next js", "Next-auth", "Firebase"],
    details:
      "This is aNn Instagram clone application I developed .users can login with their gmail details , create ,comment and like on posts",
  },
  {
    id: 602,
    project: "FACEBOOK CLONE",
    role: "FullStack Developer",
    img: "https://res.cloudinary.com/isreal/image/upload/v1676589265/My%20portfolio%20Project/Screenshot_2023-02-17_at_00.12.43_ryqcof.png",
    source_code: "https://github.com/JusticeIsreal/facebook-clone",
    live_project: "https://facebookclone-green.vercel.app",
    Technology: ["Tailwind", "Next js", "Next-auth", "Firebase"],
    details:
      "This is a facebook clone application I developed for educational purposes.users can login with their facebook details",
  },
  {
    id: 603,
    project: "BOOK RENTALS",
    role: "Frontend Developer",
    img: "https://res.cloudinary.com/isreal/image/upload/v1678478100/My%20portfolio%20Project/Screenshot_2023-03-04_at_01.46.47_pdu105.png",
    source_code: "https://github.com/JusticeIsreal/Book-rentals-clients-side",
    live_project: "",
    Technology: ["Sass", "React js"],
    details:
      "This is a book rental application consumming the backend API and client side services",
  },
  {
    id: 604,
    project: "BOOK RENTALS API",
    role: "Backend Developer",
    img: "https://res.cloudinary.com/isreal/image/upload/v1678478689/My%20portfolio%20Project/WhatsApp_Image_2023-02-27_at_12.33.06_PM_x1xtfi.jpg",
    source_code: "https://github.com/JusticeIsreal/book-rental-API",
    live_project: "",
    Technology: ["Node js", "express js"],
    details:
      "This is a book rental API for users authentication and admin CRUD operation",
  },
  {
    id: 60,
    project: "WEB HOSTING",
    role: "Frontend Developer",
    img: "https://res.cloudinary.com/isreal/image/upload/v1675470619/My%20portfolio%20Project/Screenshot_2023-02-04_at_00.59.40_ird9g5.png",
    source_code: "",
    live_project: "https://dublick.com",
    Technology: ["HTML", "SCSS", "JavaScript", "php", "MySQL"],
    details:
      "This is a web hosting company offers fast and secure servers with 24/7 customer support.",
  },
  {
    id: 50,
    project: "REAL ESTATE",
    role: "Scrum master",
    img: "https://res.cloudinary.com/isreal/image/upload/v1675470887/My%20portfolio%20Project/Screenshot_2023-02-04_at_00.58.24_wupmky.png",
    source_code: "",
    live_project: "https://heneveintegratedservices.com",
    Technology: ["WordPress", "php", "MySQL"],
    details:
      "This is a real estate website where users can buy lands and mak reservations for site inspections",
  },
  {
    id: 6,
    project: "MOVIE APP",
    role: "Frontend Developer",
    img: "https://res.cloudinary.com/isreal/image/upload/v1661847636/My%20portfolio%20Project/jayflix_ysaoce.png",
    source_code: "https://github.com/JusticeIsreal/JAYFLIX-MOVIE-APP.git",
    live_project: "https://jayflix-movie-app.vercel.app/",
    Technology: ["HTML", "SCSS", "React js"],
    details:
      "JAYFLIX is a movie web application that enables it users view avaliable Nigeria movies. This application allows the user to select from list of avaliable movies It also have the functionality where users can add movies to watch list",
  },

  {
    id: 1,
    project: "DENTAL CARE",
    role: "Full stack Developer",
    img: "https://res.cloudinary.com/isreal/image/upload/v1661847017/My%20portfolio%20Project/Jniz-care_pydzbm.png",
    source_code: "https://github.com/JusticeIsreal/Jeniz-Teeth-Whitening.git",
    live_project: "https://jnizteethcare.netlify.app/",
    Technology: [
      "HTML",
      "CSS",
      "BootStrap",
      "JavaScript",
      "Node js",
      "Express js",
      "MongoDB",
    ],
    details:
      "This website for a Teeth Whitening Company. This website enable clients book for appointments and make reservations.",
  },
  {
    id: 7,
    project: "FIN TECH",
    role: "Full stack Developer",
    img: "https://res.cloudinary.com/isreal/image/upload/v1670800679/My%20portfolio%20Project/Screenshot_2022-12-12_at_00.01.53_fpef0t.png",
    source_code: "https://github.com/JusticeIsreal/Savings-App.git",
    live_project: "https://savings-1w513jk1u-justiceisreal.vercel.app/",
    Technology: [
      "HTML",
      "SCSS",
      "JavaScript",
      "React js",
      "Node js",
      " Express js",
      "MongoDB",
    ],
    details:
      "THis is a financial management application that enables registered users to save and send money,which can be linked to users account number.",
  },
  {
    id: 2,
    project: "E-COMMERCE",
    role: "Frontend Developer",
    img: "https://res.cloudinary.com/isreal/image/upload/v1661847013/My%20portfolio%20Project/e-com_yfkzhl.png",
    source_code: "https://github.com/JusticeIsreal/E-commerce.git",
    live_project: "http://justiceecom.netlify.app",
    Technology: ["HTML", "CSS", "JavaScript"],
    details:
      "E-commerce store for small scale businesses, Admin can add product to the store, Pick a category, Pick a class, Select price and quantity. edit existing and delete product from store.",
  },
  {
    id: 3,
    project: "PERIODIC TABLE",
    role: "Frontend Developer",
    img: "https://res.cloudinary.com/isreal/image/upload/v1661847045/My%20portfolio%20Project/periodic-table_c20jxk.png",
    source_code:
      "https://github.com/JusticeIsreal/Periodic-table-with-CSS-grid.git",
    live_project: "https://justiceperiodictable.netlify.app/",
    Technology: ["HTML", "CSS", "JavaScript"],
    details: "All the elements of the periodic table and their properties",
  },
  {
    id: 8,
    project: "AJIS WEBSITE",
    role: "Frontend Developer",
    img: "https://res.cloudinary.com/isreal/image/upload/v1670800687/My%20portfolio%20Project/Screenshot_2022-12-12_at_00.01.18_n0do8p.png",
    source_code: "https://github.com/JusticeIsreal/Ajis-official-website.git",
    live_project: "",
    Technology: ["HTML", "SCSS", "React js"],
    details:
      "This project would develop0ed as a means to proferr solution to seondary school childreen who find it difficult to asccess tghe elemments of the periodic table",
  },
  {
    id: 4,
    project: "LOGISTICS",
    role: "Frontend Developer",
    img: "https://res.cloudinary.com/isreal/image/upload/v1661846998/My%20portfolio%20Project/drone-app_fvk1yy.png",
    source_code:
      "https://github.com/JusticeIsreal/Drone-Rental-Services-Company.git",
    live_project: "https://justicedronecompany.netlify.app/",
    Technology: [
      "HTML",
      "SCSS",
      "JavaScript",
      "Node js",
      "Express js",
      "MongoDB",
    ],
    details:
      "This is a web application for Drone Rental Services. it enable customers order a drone to do a delievery service in times of emegency on category ranging from REGULAR TO STANDARD TO PREMIUM",
  },
  {
    id: 5,
    project: "HEALTH CARE",
    role: "Scrum master",
    img: "https://res.cloudinary.com/isreal/image/upload/v1661847041/My%20portfolio%20Project/medical-app_m4t1di.png",
    source_code: "/",
    live_project: "https://brilliant-beijinho-78dad5.netlify.app/",
    Technology: [
      "HTML",
      "SCSS",
      "Next js",
      "TypeScript",
      "Node js",
      "Express js",
      "MongoDB",
    ],
    details:
      "This is a Diagnose product that provides you with the most recent and reliable medical diagnoses and prescrition when administering medications and medical prescription.",
  },
  {
    id: 9,
    project: "TASK MANAGER",
    role: "Full stack Developer",
    img: "https://res.cloudinary.com/isreal/image/upload/v1675470545/My%20portfolio%20Project/Screenshot_2023-02-04_at_01.21.33_wwg1be.png",
    source_code:
      "https://github.com/JusticeIsreal/FULL-STACK-TASK-MANAGER-APP.git",
    live_project: "",
    Technology: [
      "HTML",
      "SCSS",
      "React js",
      " Node js",
      "Express js",
      "MongoDB",
    ],
    details:
      "This is a task manager that enable users to register, login in and create individual tasks.. ",
  },
  {
    id: 90,
    project: "DIGITAL IV",
    role: "Full stack Developer",
    img: "https://res.cloudinary.com/isreal/image/upload/v1670800770/My%20portfolio%20Project/Screenshot_2022-12-12_at_00.19.10_m1el4x.png",
    source_code:
      "https://github.com/JusticeIsreal/Digital-wedding-invitation.git",
    live_project: "https://jj2022.vercel.app/",
    Technology: [
      "HTML",
      "SCSS",
      "React js",
      " Node js",
      "Express js",
      "MongoDB",
    ],
    details:
      "The platform allows invitees to reserve their seat and receive a unique barcode as their gate pass ID. The platform is fully automated and features an easy-to-use admin dashboard.",
  },
];

export default Projects;
