import React, { useEffect, useState } from "react";
import Head from "next/head";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

const Home: React.FC = () => {
  // firebase
  // For Firebase JS SDK v7.20.0 and later, measurementId is optional

  return (
    <div className="linktree-main-con">
      <Head>
        <title>JUSTICE ISREAL AGBONMA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="" />
      </Head>
      <div className="linktree-con">
        <div className="top">
          <div className="top-img">
            <img
              src="https://res.cloudinary.com/isreal/image/upload/v1690675954/My%20portfolio%20Project/1671744344371-removebg-preview_dxwbbb_Background_Removed_eh44ec.png"
              alt=""
            />
          </div>
          <div>
            <h1>JUSTICE ISREAL AGBONMA</h1>
            <p>" If I can conceive it, I can acheive it "</p>
          </div>
        </div>

        <div className="lower">
          <a href="" className="single-link">
            <div>
              <img src="" alt="" />
            </div>
            <p>Personal website</p>
          </a>
          <a href="" className="single-link">
            <div>
              <img src="" alt="" />
            </div>
            <p>LinkedIn</p>
          </a>
          <a href="" className="single-link">
            <div>
              <img src="" alt="" />
            </div>
            <p>Instagram</p>
          </a>
          <a href="" className="single-link">
            <div>
              <img src="" alt="" />
            </div>
            <p>Twitter</p>
          </a>
          <a href="" className="single-link">
            <div>
              <img src="" alt="" />
            </div>
            <p>Facebook</p>
          </a>
          <a href="" className="single-link">
            <div>
              <img src="" alt="" />
            </div>
            <p>Whatsapp</p>
          </a>
        </div>
      </div>
    </div>
  );
};
export default Home;
